version: "3.8"

services:
  back-end:
    build: ./back-end
    container_name: back-end
    ports:
      - 3000:3000
    volumes:
      - ./back-end:/back-end

  front-end:
    build: ./front-end
    container_name: front-end
    depends_on: 
      - back-end
    ports:
      - 4200:4200
    volumes:
      - ./front-end:/front-end
